### ISSUE TITLE
Prototipo RA

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-equipo-balam#1]
[PrototipoRA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-equipo-balam/files/10843417/PrototipoRA.pdf)

**Comment by carlos-chrs** [comment]
bien hecho..
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
